  group: 
    slice_timing: 
      type_scanner: Siemens
      type_acquisition: interleaved ascending
    t1_preprocess:  
      nu_correct:
        arg: -distance 50
    psom:
      max_queued: 5000
  198-200:
    t1_preprocess:
      nu_correct:
        arg: -distance 55
  300,301:
    slice_timing:
      type_scanner: Bruker
    t1_preprocess:
      nu_correct:
        arg: -distance 49
  303:
    t1_preprocess:
      nu_correct:
        arg: -distance 51
  304:
    t1_preprocess:
      nu_correct:
        arg: -distance 51
